on:
  workflow_dispatch:
  push:
    branches: [ master ]
  schedule:
    - cron:  '0 15 * * 0'

name: Build and deploy on push
jobs:
  build:
    name: zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: shalzz/zola-deploy-action
      uses: shalzz/zola-deploy-action@master
      env:
        PAGES_BRANCH: gh-pages
        BUILD_DIR: .
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
